application:  gae-django-cms-prac
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /js
  static_dir: js

- url: /.*
  script: main.app

libraries:
- name: django
  version: 1.5
