application:  gae-django-cms-prac
version: 1
runtime: python27
api_version: 1
threadsafe: true # change back to true

handlers:

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /js
  static_dir: js

- url: /.*
  script: main.app

libraries:
- name: django
  version: 1.5
